/**
 * Sample Movie Emotional Profiles
 * 
 * These are manually scored using the archetype + adjustment method.
 * Used to bootstrap the mood engine before full database population.
 */

import type { MovieEmotionalData } from './mood-engine';

export const SAMPLE_MOVIE_PROFILES: MovieEmotionalData[] = [
  // LIGHT ARCHETYPE
  {
    movieId: 1,
    tmdbId: 346698,
    title: "Paddington 2",
    archetype: 'light',
    emotionalProfile: {
      emotionalIntensity: 3,
      mentalStimulation: 2,
      comfort: 9,
      energy: 4,
      darkness: 0,
      humour: 7,
      complexity: 2,
      rewatchability: 9,
    },
  },
  {
    movieId: 2,
    tmdbId: 508439,
    title: "Soul",
    archetype: 'light',
    emotionalProfile: {
      emotionalIntensity: 5,
      mentalStimulation: 4,
      comfort: 8,
      energy: 4,
      darkness: 1,
      humour: 5,
      complexity: 4,
      rewatchability: 8,
    },
  },
  {
    movieId: 3,
    tmdbId: 862,
    title: "Toy Story",
    archetype: 'light',
    emotionalProfile: {
      emotionalIntensity: 4,
      mentalStimulation: 2,
      comfort: 9,
      energy: 5,
      darkness: 1,
      humour: 7,
      complexity: 2,
      rewatchability: 10,
    },
  },
  {
    movieId: 4,
    tmdbId: 194662,
    title: "Birdman",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 7,
      mentalStimulation: 8,
      comfort: 2,
      energy: 6,
      darkness: 6,
      humour: 4,
      complexity: 8,
      rewatchability: 6,
    },
  },
  
  // FUN ARCHETYPE
  {
    movieId: 5,
    tmdbId: 161,
    title: "Ocean's Eleven",
    archetype: 'fun',
    emotionalProfile: {
      emotionalIntensity: 4,
      mentalStimulation: 5,
      comfort: 7,
      energy: 7,
      darkness: 2,
      humour: 6,
      complexity: 4,
      rewatchability: 9,
    },
  },
  {
    movieId: 6,
    tmdbId: 22,
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    archetype: 'fun',
    emotionalProfile: {
      emotionalIntensity: 5,
      mentalStimulation: 3,
      comfort: 6,
      energy: 8,
      darkness: 2,
      humour: 7,
      complexity: 3,
      rewatchability: 8,
    },
  },
  {
    movieId: 7,
    tmdbId: 8587,
    title: "The Lion King",
    archetype: 'fun',
    emotionalProfile: {
      emotionalIntensity: 6,
      mentalStimulation: 2,
      comfort: 7,
      energy: 6,
      darkness: 3,
      humour: 6,
      complexity: 2,
      rewatchability: 10,
    },
  },
  {
    movieId: 8,
    tmdbId: 120467,
    title: "The Grand Budapest Hotel",
    archetype: 'fun',
    emotionalProfile: {
      emotionalIntensity: 4,
      mentalStimulation: 5,
      comfort: 6,
      energy: 6,
      darkness: 3,
      humour: 8,
      complexity: 5,
      rewatchability: 8,
    },
  },
  
  // STIMULATING ARCHETYPE
  {
    movieId: 9,
    tmdbId: 27205,
    title: "Inception",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 7,
      mentalStimulation: 9,
      comfort: 3,
      energy: 8,
      darkness: 4,
      humour: 2,
      complexity: 9,
      rewatchability: 8,
    },
  },
  {
    movieId: 10,
    tmdbId: 329865,
    title: "Arrival",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 9,
      comfort: 3,
      energy: 4,
      darkness: 5,
      humour: 0,
      complexity: 9,
      rewatchability: 7,
    },
  },
  {
    movieId: 11,
    tmdbId: 155,
    title: "The Dark Knight",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 7,
      comfort: 2,
      energy: 8,
      darkness: 7,
      humour: 2,
      complexity: 6,
      rewatchability: 9,
    },
  },
  {
    movieId: 12,
    tmdbId: 68718,
    title: "Django Unchained",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 5,
      comfort: 2,
      energy: 7,
      darkness: 8,
      humour: 5,
      complexity: 4,
      rewatchability: 7,
    },
  },
  {
    movieId: 13,
    tmdbId: 550,
    title: "Fight Club",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 9,
      comfort: 1,
      energy: 7,
      darkness: 8,
      humour: 5,
      complexity: 9,
      rewatchability: 9,
    },
  },
  {
    movieId: 14,
    tmdbId: 680,
    title: "Pulp Fiction",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 7,
      mentalStimulation: 7,
      comfort: 3,
      energy: 6,
      darkness: 7,
      humour: 7,
      complexity: 8,
      rewatchability: 9,
    },
  },
  
  // DEEP ARCHETYPE
  {
    movieId: 15,
    tmdbId: 424,
    title: "Schindler's List",
    archetype: 'deep',
    emotionalProfile: {
      emotionalIntensity: 10,
      mentalStimulation: 6,
      comfort: 0,
      energy: 4,
      darkness: 10,
      humour: 0,
      complexity: 5,
      rewatchability: 4,
    },
  },
  {
    movieId: 16,
    tmdbId: 334543,
    title: "Manchester by the Sea",
    archetype: 'deep',
    emotionalProfile: {
      emotionalIntensity: 9,
      mentalStimulation: 5,
      comfort: 1,
      energy: 2,
      darkness: 8,
      humour: 2,
      complexity: 5,
      rewatchability: 4,
    },
  },
  {
    movieId: 17,
    tmdbId: 637,
    title: "Life Is Beautiful",
    archetype: 'deep',
    emotionalProfile: {
      emotionalIntensity: 10,
      mentalStimulation: 5,
      comfort: 4,
      energy: 4,
      darkness: 7,
      humour: 6,
      complexity: 4,
      rewatchability: 6,
    },
  },
  {
    movieId: 18,
    tmdbId: 389,
    title: "3 Idiots",
    archetype: 'fun',
    emotionalProfile: {
      emotionalIntensity: 6,
      mentalStimulation: 4,
      comfort: 7,
      energy: 6,
      darkness: 2,
      humour: 8,
      complexity: 3,
      rewatchability: 9,
    },
  },
  {
    movieId: 19,
    tmdbId: 19404,
    title: "Dilwale Dulhania Le Jayenge",
    archetype: 'light',
    emotionalProfile: {
      emotionalIntensity: 5,
      mentalStimulation: 2,
      comfort: 9,
      energy: 5,
      darkness: 1,
      humour: 6,
      complexity: 2,
      rewatchability: 10,
    },
  },
  {
    movieId: 20,
    tmdbId: 238,
    title: "The Godfather",
    archetype: 'deep',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 7,
      comfort: 2,
      energy: 4,
      darkness: 9,
      humour: 1,
      complexity: 7,
      rewatchability: 8,
    },
  },
  
  // Additional movies for variety
  {
    movieId: 21,
    tmdbId: 244786,
    title: "Whiplash",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 9,
      mentalStimulation: 6,
      comfort: 1,
      energy: 8,
      darkness: 6,
      humour: 2,
      complexity: 4,
      rewatchability: 8,
    },
  },
  {
    movieId: 22,
    tmdbId: 496243,
    title: "Parasite",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 9,
      mentalStimulation: 8,
      comfort: 1,
      energy: 7,
      darkness: 8,
      humour: 5,
      complexity: 8,
      rewatchability: 8,
    },
  },
  {
    movieId: 23,
    tmdbId: 13,
    title: "Forrest Gump",
    archetype: 'light',
    emotionalProfile: {
      emotionalIntensity: 6,
      mentalStimulation: 3,
      comfort: 8,
      energy: 4,
      darkness: 3,
      humour: 5,
      complexity: 3,
      rewatchability: 9,
    },
  },
  {
    movieId: 24,
    tmdbId: 489,
    title: "Good Will Hunting",
    archetype: 'deep',
    emotionalProfile: {
      emotionalIntensity: 8,
      mentalStimulation: 6,
      comfort: 4,
      energy: 3,
      darkness: 5,
      humour: 4,
      complexity: 5,
      rewatchability: 8,
    },
  },
  {
    movieId: 25,
    tmdbId: 568332,
    title: "Everything Everywhere All at Once",
    archetype: 'stimulating',
    emotionalProfile: {
      emotionalIntensity: 9,
      mentalStimulation: 9,
      comfort: 5,
      energy: 9,
      darkness: 4,
      humour: 7,
      complexity: 9,
      rewatchability: 8,
    },
  },
];

// Export as JSON string for easy copy-paste to database
export const SAMPLE_PROFILES_JSON = JSON.stringify(SAMPLE_MOVIE_PROFILES, null, 2);
